#!/usr/bin/bash

read -p "Program name: " name
git clone "https://www.github.com/user-firepluto/$name" /home/$USER/.pluto-temp/"$name"
cd /home/$USER/.pluto-temp/"$name" && chmod +x installer.sh && ./installer.sh
sudo rm -rf /home/$USER/.pluto-temp/"$name"
echo "Installation of the program ($name) is sucefully completed"
